#+TITLE: JtoE Games Translator
#+AUTHOR: Daniel Otto

#+TAGS: noexport(n) ignore(I)

* Config                                                      :noexport:ignore:

This branch is based off of the config found [[https://www.aidanscannell.com/post/org-mode-resume/][here]].

#+begin_src elisp :results none
(org-export-to-file 'altacv "altacv.tex")
(org-latex-compile "altacv.tex")
#+end_src

** TODO Guix

#+begin_src scheme
"font-google-roboto"
"font-lato"
"font-awesome"
#+end_src

** TODO Move LaTeX Config to standard export
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
(add-to-list 'org-latex-classes
             '("altacv" "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

% Change the page layout if you need to
\\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

% Use roboto and lato for fonts
\\renewcommand{\\familydefault}{\\sfdefault}

% Change the colours if you want to
\\RequirePackage{xcolor}
\\definecolor{draculabg}      {RGB} {40,   42,   54}
\\definecolor{draculacl}      {RGB} {68,   71,   90}
\\definecolor{draculafg}      {RGB} {248,  248,  242}
\\definecolor{draculacomment} {RGB} {98,   114,  164}
\\definecolor{draculacyan}    {RGB} {139,  233,  253}
\\definecolor{draculagreen}   {RGB} {80,   250,  123}
\\definecolor{draculaorange}  {RGB} {255,  184,  108}
\\definecolor{draculapink}    {RGB} {255,  121,  198}
\\definecolor{draculapurple}  {RGB} {189,  147,  249}
\\definecolor{draculared}     {RGB} {255,  85,   85}
\\definecolor{draculayellow}  {RGB} {241,  250,  140}
\\pagecolor{draculabg}
\\colorlet{name}{draculapurple}
\\colorlet{tagline}{draculagreen}
\\colorlet{heading}{draculacyan}
\\colorlet{headingrule}{draculayellow}
\\colorlet{subheading}{draculaorange}
\\colorlet{accent}{draculapink}
\\colorlet{emphasis}{draculacomment}
\\colorlet{body}{draculacomment}

% Change some fonts, if necessary
\\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
\\renewcommand{\\personalinfofont}{\\footnotesize}
\\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
\\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

% Change the bullets for itemize and rating marker
% for \cvskill if you want to
\\renewcommand{\\itemmarker}{{\\small\\textbullet}}
\\renewcommand{\\ratingmarker}{\\faCircle}
"

               ("\\cvsection{%s}" . "\\cvsection*{%s}")
               ("\\cvevent{%s}" . "\\cvevent*{%s}")))
(setq org-latex-packages-alist 'nil)
(setq org-latex-default-packages-alist
      '(("rm" "roboto"  t)
        ("defaultsans" "lato" t)
        ("" "paracol" t)
        ))
#+END_SRC
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.
#+LATEX_HEADER: \usepackage{luatexja}
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{longtable}
#+LATEX_HEADER: \usepackage{wrapfig}
#+LATEX_HEADER: \usepackage{rotating}
#+LATEX_HEADER: \usepackage[normalem]{ulem}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{amssymb}
#+LATEX_HEADER: \usepackage{capt-of}
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_CLASS: altacv

** Exporter Settings
#+AUTHOR: Daniel Otto
#+EXPORT_FILE_NAME: cv.pdf
#+OPTIONS: toc:nil title:nil H:1

** Macros
#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider
#+MACRO: new-page \newpage

* CV header                                                            :ignore:
** Photo & tagline                                                    :ignore:
#+begin_export latex
\name{Daniel Otto}
% \photoR{2.8cm}{aidan_portrait.jpeg}
\tagline{Games Localiser}
#+end_export

** Personal info                                                      :ignore:
#+begin_export latex
\personalinfo{
  \homepage{www.danielotto.jp}
  \email{translation@danielotto.jp}
  \phone{+81 80 7650 1991}
  \location{Tokyo, Japan}
  \github{nanjigen}
  \linkedin{dmotto}
  \dob{1991/10/18}
}
\makecvheader
#+end_export

* CV Column one                                                        :ignore:
** config

#+begin_export latex
\begin{paracol}{2}
#+end_export

** Experience
*** Freelance translator
{{{cvevent(Freelance translator, self-employed, Sept 2017 -- Ongoing, Tokyo\, Japan)}}}
Japanese to English game localisation and linguistic quality assurance over both mobile and console titles.
** Projects
{{{par-div}}}
*** PS4 Title for large publisher
- (Ongoing, currently under NDA)
*** Cat Painter「ネコの絵描きさん」
- Android, iOS/Waken
*** Shadowverse
- eSports coverage materials/Cygames
** Volunteering
*** EVO Japan

* CV Column two                                                        :ignore:
#+begin_export latex
\switchcolumn
#+end_export

** Languages
#+begin_export latex
% \cvsection{Languages}

\cvskill{English - Native}{5}
% \divider

\cvskill{Japanese - N2}{4}
% \divider

% \cvskill{German}{3}

% %% Yeah I didn't spend too much time making all the
% %% spacing consistent... sorry. Use \smallskip, \medskip,
% %% \bigskip, \vpsace etc to make ajustments.
% \medskip
#+end_export
** Education
*** Honours in Linguistics
{{{cvevent(PhD\ in Bayesian Machine Learning for Robotic Control, University of Bristol, Sept 2018 - Ongoing,)}}}
Ongoing eye-tracking research with human participants, studying the effect of
various types of flashcard formatting on acquisition of academic terms in a
second language.
*** Bachelor of Arts
{{{cvevent(BA\ in Linguistics and Japanese Studies, University of New South Wales, Sept 2018 - Ongoing,)}}}
Majored in Linguistics and Japanese Studies. This included the study of
Japanese and Japanese history and culture. The Linguistics studies focused
on pragmatics, semantics, syntactic and morphemic analysis and phonology.
Courses were also done in psycholinguistics and second language acquisition.
*** My Life Philosophy                                              :noexport:
*** Achievements                                                    :noexport:
** Technical Skills
- CAT Tools
- CafeTrans and OmegaT
- Subtitling
- Aegisubs
- Software
- Matlab, Microsoft Excel, Unix/Linux(Arch), Vim, Emacs
- Programming
- Python, LATEX, BASH

** Referees                                                         :noexport:
** Backmatter                                                         :ignore:

#+begin_export latex
\end{paracol}
#+end_export

** No export                                                        :noexport:
;* COMMENT local variables

;# Local Variables:
;# org-latex-with-hyperref: nil
;# org-latex-packages-alist: nil
;# org-latex-default-packages-alist: (("rm" "roboto"  t) ("defaultsans" "lato" t) ("" "paracol" t)))
;# End:
