#+TITLE: JtoE Games Translator
#+AUTHOR: Daniel Otto

#+TAGS: noexport(n) ignore(I)

* Config                                                      :noexport:ignore:

This branch is based off of the config found [[https://www.aidanscannell.com/post/org-mode-resume/][here]].

#+begin_src elisp :results none
(org-export-to-file 'altacv "altacv.tex")
(org-latex-compile "altacv.tex")
#+end_src

** TODO Guix

#+begin_src scheme
"font-google-roboto"
"font-lato"
"font-awesome"
#+end_src

** TODO Move LaTeX Config to standard export
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
(add-to-list 'org-latex-classes
             '("altacv" "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

% Change the page layout if you need to
\\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

% Use roboto and lato for fonts
\\renewcommand{\\familydefault}{\\sfdefault}

% Change the colours if you want to
\\definecolor{SlateGrey}{HTML}{2E2E2E}
\\definecolor{LightGrey}{HTML}{666666}
\\definecolor{DarkPastelRed}{HTML}{450808}
\\definecolor{PastelRed}{HTML}{8F0D0D}
\\definecolor{GoldenEarth}{HTML}{E7D192}
\\colorlet{name}{black}
\\colorlet{tagline}{PastelRed}
\\colorlet{heading}{DarkPastelRed}
\\colorlet{headingrule}{GoldenEarth}
\\colorlet{subheading}{PastelRed}
\\colorlet{accent}{PastelRed}
\\colorlet{emphasis}{SlateGrey}
\\colorlet{body}{LightGrey}

% Change some fonts, if necessary
\\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
\\renewcommand{\\personalinfofont}{\\footnotesize}
\\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
\\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

% Change the bullets for itemize and rating marker
% for \cvskill if you want to
\\renewcommand{\\itemmarker}{{\\small\\textbullet}}
\\renewcommand{\\ratingmarker}{\\faCircle}
"

               ("\\cvsection{%s}" . "\\cvsection*{%s}")
               ("\\cvevent{%s}" . "\\cvevent*{%s}")))
(setq org-latex-packages-alist 'nil)
(setq org-latex-default-packages-alist
      '(("rm" "roboto"  t)
        ("defaultsans" "lato" t)
        ("" "paracol" t)
        ))
#+END_SRC
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.
#+LATEX_HEADER: \usepackage{luatexja}
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{longtable}
#+LATEX_HEADER: \usepackage{wrapfig}
#+LATEX_HEADER: \usepackage{rotating}
#+LATEX_HEADER: \usepackage[normalem]{ulem}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{amssymb}
#+LATEX_HEADER: \usepackage{capt-of}
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_CLASS: altacv

** Exporter Settings
#+AUTHOR: Daniel Otto
#+EXPORT_FILE_NAME: cv.pdf
#+OPTIONS: toc:nil title:nil H:1

** Macros
#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider
#+MACRO: new-page \newpage

* CV header                                                            :ignore:
** Photo & tagline                                                    :ignore:
#+begin_export latex
\name{Daniel Otto}
% \photoR{2.8cm}{aidan_portrait.jpeg}
\tagline{Games Localiser}
#+end_export

** Personal info                                                      :ignore:
#+begin_export latex
\personalinfo{
  \homepage{www.danielotto.jp}
  \email{translation@danielotto.jp}
  \phone{+81 80 7650 1991}
  \location{Tokyo, Japan}
  \github{nanjigen}
  \linkedin{dmotto}
  \dob{1991/10/18}
}
\makecvheader
#+end_export

* CV Column one                                                        :ignore:
** config

#+begin_export latex
\begin{paracol}{2}
#+end_export
- (Ongoing, currently under NDA)
** Cat Painter「ネコの絵描きさん」
- Android, iOS/Waken
** Shadowverse
- eSports coverage materials/Cygames
* Volunteering
** EVO Japan

#+latex: \marginpar{
* Languages
:PROPERTIES:
:CV_ENV:   cvskills
:END:
- *English* (Native Language)
- *Japanese*
* Education
** Honours in Linguistics
:PROPERTIES:
:CV_ENV:   cvschool
:LOCATION: The University of New South Wales
:FROM: 2018
:TO: 2021
:END:
Ongoing eye-tracking research with human participants, studying the effect of
various types of flashcard formatting on acquisition of academic terms in a
second language.
** Bachelor of Arts
:PROPERTIES:
:CV_ENV:   cvschool
:LOCATION: The University of New South Wales
:FROM: 2013
:TO: 2017
:END:
Majored in Linguistics and Japanese Studies. This included the study of
Japanese and Japanese history and culture. The Linguistics studies focused
on pragmatics, semantics, syntactic and morphemic analysis and phonology.
Courses were also done in psycholinguistics and second language acquisition.
** My Life Philosophy                                               :noexport:
** Achievements                                                     :noexport:
* Technical Skills
:PROPERTIES:
:CV_ENV:   cvskills
:END:
- CAT Tools
- CafeTrans and OmegaT
- Subtitling
- Aegisubs
- Software
- Matlab, Microsoft Excel, Unix/Linux(Arch), Vim, Emacs
- Programming
- Python, LATEX, BASH

** Referees                                                         :noexport:
** Backmatter                                                         :ignore:

#+begin_export latex
\end{paracol}
#+end_export

** No export                                                        :noexport:
;* COMMENT local variables

;# Local Variables:
;# org-latex-with-hyperref: nil
;# org-latex-packages-alist: nil
;# org-latex-default-packages-alist: (("rm" "roboto"  t) ("defaultsans" "lato" t) ("" "paracol" t)))
;# End:
