#+TITLE: JtoE Games Translator
#+AUTHOR: Daniel Otto
#+EMAIL: translation@danielotto.jp

#+address: Takadanobaba
#+address: Tokyo, Japan
#+mobile: (080) 7650 1991
#+homepage: danielotto.jp
#+github: nanjigen
#+gitlab:
#+linkedin: dmotto
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.
#+LATEX_HEADER: \usepackage{luatexja}
#+TAGS: noexport(n) ignore(I)

This branch is based off of the config found [[https://www.aidanscannell.com/post/org-mode-resume/][here]].

* Config                                                             :noexport:

#+begin_src elisp :results none
(org-export-to-file 'altacv "altacv.tex")
(org-latex-compile "altacv.tex")
#+end_src

** TODO Move LaTeX Config to standard export
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
(add-to-list 'org-latex-classes
             '("altacv" "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

% Change the page layout if you need to
\\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

% Use roboto and lato for fonts
\\renewcommand{\\familydefault}{\\sfdefault}

% Change the colours if you want to
\\definecolor{SlateGrey}{HTML}{2E2E2E}
\\definecolor{LightGrey}{HTML}{666666}
\\definecolor{DarkPastelRed}{HTML}{450808}
\\definecolor{PastelRed}{HTML}{8F0D0D}
\\definecolor{GoldenEarth}{HTML}{E7D192}
\\colorlet{name}{black}
\\colorlet{tagline}{PastelRed}
\\colorlet{heading}{DarkPastelRed}
\\colorlet{headingrule}{GoldenEarth}
\\colorlet{subheading}{PastelRed}
\\colorlet{accent}{PastelRed}
\\colorlet{emphasis}{SlateGrey}
\\colorlet{body}{LightGrey}

% Change some fonts, if necessary
\\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
\\renewcommand{\\personalinfofont}{\\footnotesize}
\\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
\\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

% Change the bullets for itemize and rating marker
% for \cvskill if you want to
\\renewcommand{\\itemmarker}{{\\small\\textbullet}}
\\renewcommand{\\ratingmarker}{\\faCircle}
"

               ("\\cvsection{%s}" . "\\cvsection*{%s}")))
#+END_SRC

** Exporter Settings
#+OPTIONS: toc:nil title:nil H:1

** Macros
#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: divider \par\divider

** Photo & tagline                                                  :noexport:
** Personal info                                                    :noexport:

* Experience
** Freelance translator
:PROPERTIES:
:CV_ENV: cventry
:FROM:     <2017-12-07>
:TO:     Now
:LOCATION: Sydney, Tokyo
:EMPLOYER: The employer
:END:
- Japanese to English game localisation and linguistic quality assurance over both mobile and console titles.
* Projects
:PROPERTIES:
:CV_ENV:   cventries
:END:
** PS4 Title for large publisher
- (Ongoing, currently under NDA)
** Cat Painter「ネコの絵描きさん」
- Android, iOS/Waken
** Shadowverse
- eSports coverage materials/Cygames
* Volunteering
** EVO Japan

#+latex: \marginpar{
* Languages
:PROPERTIES:
:CV_ENV:   cvskills
:END:
- *English* (Native Language)
- *Japanese*
* Education
** Honours in Linguistics
:PROPERTIES:
:CV_ENV:   cvschool
:LOCATION: The University of New South Wales
:FROM: 2018
:TO: 2021
:END:
Ongoing eye-tracking research with human participants, studying the effect of
various types of flashcard formatting on acquisition of academic terms in a
second language.
** Bachelor of Arts
:PROPERTIES:
:CV_ENV:   cvschool
:LOCATION: The University of New South Wales
:FROM: 2013
:TO: 2017
:END:
Majored in Linguistics and Japanese Studies. This included the study of
Japanese and Japanese history and culture. The Linguistics studies focused
on pragmatics, semantics, syntactic and morphemic analysis and phonology.
Courses were also done in psycholinguistics and second language acquisition.
** My Life Philosophy                                               :noexport:
** Achievements                                                     :noexport:
* Technical Skills
:PROPERTIES:
:CV_ENV:   cvskills
:END:
- CAT Tools
- CafeTrans and OmegaT
- Subtitling
- Aegisubs
- Software
- Matlab, Microsoft Excel, Unix/Linux(Arch), Vim, Emacs
- Programming
- Python, LATEX, BASH

#+latex: }
* Referees                                                           :noexport:

* Backmatter                                                         :noexport:


* COMMENT local variables

# Local Variables:
# (org-export-to-file 'altacv "altacv.tex")
# (org-latex-compile "altacv.tex")
# End:
