#+OPTIONS: toc:nil num:nil
#+TITLE: Hi! I'm Daniel

データアナリスト・言語学者

Data Analyst and Assistant Linguistics Researcher

Previously A freelance Japanese to English translator working in the games industry, having lived and worked in Tokyo and performed localisation and LQA for some of the largest Japanese publishers. Aside from a specialisation in games and creative writing, I'm a researcher in the field of Linguistics; in the area of second language acquisition where I ply my understanding of Python and Computational Linguistics to perform analysis of Linguistic and other forms of data. I'm based in Tokyo, Japan.

My main tool of use is the venerable ~Emacs~ (in the form of the [[https://github.com/hlissner/doom-emacs][Doom Emacs]] distribution). ~Emacs~ acts as a textual interface, overlaying and assisting my work in various key translation,  programming and analysis applications. This allows me to use Vim-like modal editing in programs, improving the speed of my workflow. I also make extensive use of =org-mode= in a literate programming style, much like that found in the work flow used in Jupyter notebooks (which I use interchangeably from =org-mode= for cross-compatibility).

I have a keen interest in Computer Science and data analysis and spend my free time working on theoretical open-source programs (such as [[https://github.com/nanjigen/org-incremental][org-incremental]]) and studying LISPs and mathematics.

# If curiosity has caught your CAT tool, you can see how I work [[workflow.org][here].

If you have any inquires or would like to work with me, contact me at:
mailto:techlisper@danielotto.jp

[[file:../pdf/cv-tech-en.pdf][My C.V.]]
------

* Links
:PROPERTIES:
:CREATED:  [2022-10-09 Sun 18:12]
:ID:       543b96e7-ca83-4048-b960-c2c169adf385
:END:

  * [[url_for:blog][Blog (Under construction)]]
  * [[https://github.com/nanjigen][GitHub]]
  * [[https://linkedin.com/in/dmotto][LinkedIn]]
  * [[mailto:techlisper@danielotto.jp][Email]]
