#+TITLE: 日英ゲーム翻訳者
#+AUTHOR: Daniel Otto

#+TAGS: noexport(n) ignore(i)

* Config                                                   :noexport:ignore:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       763a784e-f2d7-4a30-90a5-4a3565241082
:END:

This branch is based off of the config found [[https://www.aidanscannell.com/post/org-mode-resume/][here]].
https://github.com/aidanscannell/my-org-resume

#+begin_src elisp :results none
(org-export-to-file 'altacv "altacv.tex")
(org-latex-compile "altacv.tex")
#+end_src

** TODO Guix
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       673be7f4-02f1-4168-a1e5-3ebd2b566730
:END:

#+begin_src scheme :tangle manifest.scm
(specifications->manifest
 (list
  "font-google-roboto"
  "font-lato"
  "font-awesome"))
#+end_src

** TODO Move LaTeX Config to standard export
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       cba8bde3-12ed-445d-b572-da9a32d75267
:END:
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
(add-to-list 'org-latex-classes
             '("altacv" "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

% Change the page layout if you need to
\\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

% Use roboto and lato for fonts
\\renewcommand{\\familydefault}{\\sfdefault}

% Change the colours if you want to
\\RequirePackage{xcolor}
\\definecolor{dracula-background}{HTML}{141d28}
\\definecolor{dracula-background-secondary-alt}{HTML}{44475a}
\\definecolor{dracula-background-secondary}{HTML}{1e1f29}
\\definecolor{dracula-foreground}{HTML}{f8f8f2}
\\definecolor{dracula-sidebar-background}{HTML}{233346}
\\definecolor{dracula-green}{HTML}{50fa7b}
\\definecolor{dracula-violet}{HTML}{bd93f9}
\\definecolor{dracula-magenta}{HTML}{ff79c6}
\\definecolor{dracula-orange}{HTML}{ffb86c}
\\definecolor{dracula-cyan}{HTML}{8be9fd}
\\definecolor{dracula-red}{HTML}{ff5555}
\\definecolor{dracula-yellow}{HTML}{f1fa8c}
\\definecolor{dracula-body-text}{HTML}{C3C3C3}
\\definecolor{dracula-comment}{HTML}{6272a4}
\\definecolor{dracula-page-links}{HTML}{C26EFF}
\\definecolor{dracula-attributes-color}{HTML}{FFFF80}
\\definecolor{dracula-external-links}{HTML}{7CE973}
\\definecolor{dracula-links-hover}{HTML}{92FFFF}
\\definecolor{dracula-hashtags}{HTML}{FFD17E}
\\definecolor{dracula-italics-color}{HTML}{FF7EA2}
\\definecolor{dracula-bold-color}{HTML}{FF4E4E}
\\definecolor{dracula-highlight-text-color}{HTML}{47405E}
\\definecolor{dracula-highlighter}{HTML}{FFFF80}
\\definecolor{dracula-sidebar-text}{HTML}{F2F2F2}
\\definecolor{dracula-page-heading}{HTML}{FFBE49}
\\definecolor{dracula-daily-heading}{HTML}{FFCA6A}
\\definecolor{dracula-headings}{HTML}{F2F2F2}
\\definecolor{dracula-bullets}{HTML}{7A6DAA}
\\definecolor{dracula-closed-bullets}{HTML}{3E445D}
\\definecolor{dracula-references}{HTML}{9E8DDB}
\\definecolor{dracula-block-reference-text}{HTML}{FF9580}
\\definecolor{dracula-namespaces}{HTML}{5EB9FF}
\\definecolor{dracula-all-pages-mentions}{HTML}{FF9580}
\\definecolor{dracula-cursor}{HTML}{F2F2F2}
\\definecolor{dracula-icons}{HTML}{FBCC77}
\\definecolor{dracula-icons-hover}{HTML}{81FFEA}
\\definecolor{dracula-filter-icon}{HTML}{C26EFF}
\\pagecolor{white}
\\colorlet{name}{dracula-violet}
\\colorlet{tagline}{dracula-red}
\\colorlet{heading}{dracula-namespaces}
\\colorlet{headingrule}{dracula-bullets}
\\colorlet{subheading}{dracula-orange}
\\colorlet{accent}{dracula-page-links}
\\colorlet{emphasis}{dracula-comment}
\\colorlet{body}{dracula-background}

% Change some fonts, if necessary
\\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
\\renewcommand{\\personalinfofont}{\\footnotesize}
\\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
\\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

% Change the bullets for itemize and rating marker
% for \cvskill if you want to
\\renewcommand{\\itemmarker}{{\\small\\textbullet}}
\\renewcommand{\\ratingmarker}{\\faCircle}
"

               ("\\cvsection{%s}" . "\\cvsection*{%s}")
               ("\\cvevent{%s}" . "\\cvevent*{%s}")))
(setq org-latex-packages-alist 'nil)
(setq org-latex-default-packages-alist
      '(("rm" "roboto"  t)
        ("defaultsans" "lato" t)
        ("" "paracol" t)
        ))
#+END_SRC
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.
#+LATEX_HEADER: \usepackage{luatexja}
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{longtable}
#+LATEX_HEADER: \usepackage{wrapfig}
#+LATEX_HEADER: \usepackage{rotating}
#+LATEX_HEADER: \usepackage[normalem]{ulem}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{amssymb}
#+LATEX_HEADER: \usepackage{capt-of}
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_CLASS: altacv

** Exporter Settings
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       8b14a310-3fe1-47e0-b076-0a2020f115ce
:END:
#+AUTHOR: Daniel Otto
#+EXPORT_FILE_NAME: cv.pdf
#+OPTIONS: toc:nil title:nil H:1

** Macros
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       73320694-1492-4f7b-bc52-fbea9abcf4b6
:END:
#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider
#+MACRO: new-page \newpage

* CV header                                                            :ignore:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       68925e07-c55c-4111-a74b-59fac438df07
:END:
** Photo & tagline                                                    :ignore:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       ae004d2b-9221-4c33-9163-84bde39ef094
:END:
#+begin_export latex
\name{Daniel Otto}
% \photoR{2.8cm}{profile.jpeg}
\tagline{ゲームローカライザー}
#+end_export

** Personal info                                                      :ignore:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       fc3a460e-5487-4f5c-800a-5c744d591684
:END:
#+begin_export latex
\personalinfo{
  \homepage{www.danielotto.jp}
  \email{translation@danielotto.jp}
  \phone{+81 80 7650 1991}
  \location{新宿区、東京}
  \github{nanjigen}
  \linkedin{dmotto}
  \dob{1991/10/18}
}
\makecvheader
#+end_export

* CV Column one                                                        :ignore:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       3fd07963-474a-4c5c-8b60-660af3858e4c
:END:
** config                                                             :ignore:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       4e0e343b-cabb-40f0-ab5a-332cf2b461b1
:END:

#+begin_export latex
\begin{paracol}{2}
#+end_export

** 経験歴
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       cffb58a9-d978-4aff-a67f-a9f38bcdeae6
:END:
*** 英会話先生                                                       :ignore:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       d5d8b9ad-05ad-47b6-aece-3b062a0da982
:END:
{{{cvevent(英会話先生, NOVA, 2022年04月～現在, 東京\、日本)}}}
水際対策の際、入国審査が緩和され、日本への入国ビザが取得できた。言語学と第二言語習得の専門知識を活かし、日本人に英語を教えています。
{{{par-div}}}

*** Freelance translator                                             :ignore:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       d40c946e-9143-4df9-a58c-daf68580499a
:END:
{{{cvevent(フリーランス翻訳者, 個人事業主, 2017/09 -- 継続中, 東京、シドニー)}}}
日本とオーストラリアを行き来しながら、モバイルとコンソールのゲームローカライゼーションと言語的品質保証を担当。
{{{par-div}}}

** プロジェクト
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       5f53e07c-705c-44d4-945d-70609d4be5cf
:END:
*** Cat Painter「ネコの絵描きさん」                                  :ignore:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       af9d7fc9-8871-4ed2-b016-1ccc4e361441
:END:
{{{cvevent(Cat Painter「ネコの絵描きさん」, 「Nukenin社よりImpetus業務を受託」, 2019年05月～2020年03月, シドニー\、オーストラリア)}}}
- Android, iOS/Waken
*** PS4 Title for large publisher                                    :ignore:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       9f9e5dd4-278e-4eb0-9744-07cd0034c651
:END:
{{{cvevent(西遊記, 「SIE社よりImpetus業務を受託」, 2018年04月～2019年04月, 東京\、日本)}}}
- (以前はNDA) Q/Aタスク、アイテム翻訳、武道関連用語のアドバイスなどを実施。
*** Shadowverse                                                      :ignore:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       18fd4fe5-a465-437f-bfb6-e379693f16c0
:END:
{{{cvevent(Shadowverse, 「Cygames社よりImpetus業務を受託」, 2017年11月～2018年03月, 東京\、日本)}}}
- RAGE　Shadowverse　World　Grand　Prix eスポーツ取材資料

** ボランティア
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       6bab089e-d07e-4383-8abf-913353e2d5e9
:END:
*** EVO Japan                                                        :ignore:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       f437c105-09e1-4de7-b0f5-f86205d4ca14
:END:
{{{cvevent(EVO Japan, EVO, 2018, 東京\、日本)}}}

*** Various Japan Film Festivals                                     :ignore:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       252f8d3f-b594-41ee-8e06-632a09fb7951
:END:
{{{cvevent(JFF（日本映画祭）, Japan Foundation, 2013 -- 2017, オーストラリア シドニー、パース)}}}
シドニー、パース

* CV Column two                                                        :ignore:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       a090fdd0-e9a6-4603-ae11-5c7176eaa8d5
:END:
#+begin_export latex
\switchcolumn
#+end_export

** 言語
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       8724de14-bcd3-4c3e-917c-e6085e98df85
:END:
#+begin_export latex
% \cvsection{Languages}

\cvskill{英語 - 母語}{5}
% \divider

\cvskill{日本語 - JLPT N2}{4}
% \divider

% \cvskill{German}{3}

% %% Yeah I didn't spend too much time making all the
% %% spacing consistent... sorry. Use \smallskip, \medskip,
% %% \bigskip, \vpsace etc to make ajustments.
% \medskip
#+end_export
** 学歴
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       6a2dc4c5-12e6-4454-befe-6bd2829f2ec6
:END:
*** Honours in Linguistics                                           :ignore:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       c8617345-4733-4228-9312-a4887d60029c
:END:
{{{cvevent(言語学専攻の優等生, ニューサウスウェールズ大学, Sept 2018 - 継続中)}}}
フラッシュカードの様々なフォーマットが第二言語の学術用語の習得に及ぼす影響について、ヒト被験者を対象としたアイトラッキング研究を継続中。
{{{par-div}}}
*** Bachelor of Arts                                                 :ignore:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       4b2cc4f9-aabd-47f1-8ad9-4bcce12bbf17
:END:
{{{cvevent(言語学および日本研究専攻の学士号, ニューサウスウェールズ大学, 2013 - 2017)}}}
その中には、日本や日本の歴史や文化を学ぶことも含まれていました。言語学では、語用論、意味論、構文・形態素解析、音韻論に焦点を当てました。また、心理言語学や第二言語習得のコースも行われました。

*** My Life Philosophy                                              :noexport:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       122c6e71-83d3-4240-a18e-a200a12de781
:END:
*** Achievements                                                   :noexport:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       559de65d-8a9c-4acb-bede-81b313fb2339
:END:

** 技術力
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       7252a5a1-4cab-4504-985b-a08966f94bc8
:END:
- CAT ツール
{{{cvtag(OmegaT)}}}
{{{cvtag(MemoQ)}}}
- 字幕
{{{cvtag(Aegisub)}}}
- ソフトウェア
{{{cvtag(Microsoft Excel)}}}
{{{cvtag(GNU/Linux)}}}
{{{cvtag(Emacs)}}}
{{{cvtag(Vim)}}}
- プログラミング
{{{cvtag(Python)}}}
{{{cvtag(LISP)}}}
{{{cvtag(\LaTeX)}}}
{{{cvtag(BASH)}}}

#+begin_export latex
\end{paracol}
#+end_export

** Referees                                                         :noexport:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       f2a3ea85-d331-4925-965c-99894015cc0b
:END:
** Backmatter                                                         :ignore:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       731a1322-ab42-49ff-ab0d-02d498691dd5
:END:

** No export                                                        :noexport:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:54]
:ID:       00aa3c41-49f8-4ea5-91fb-bbec2125e866
:END:
;* COMMENT local variables

;# Local Variables:
;# org-latex-with-hyperref: nil
;# org-latex-packages-alist: nil
;# org-latex-default-packages-alist: (("rm" "roboto"  t) ("defaultsans" "lato" t) ("" "paracol" t)))
;# End:
