#+TITLE: Data Analyst
#+AUTHOR: Daniel Otto

#+TAGS: noexport(n) ignore(i)

* Config                                                   :noexport:ignore:
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       36577db3-9870-4b34-8d27-5a637df99fd1
:END:

This branch is based off of the config found [[https://www.aidanscannell.com/post/org-mode-resume/][here]].

** TODO Guix
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       07be475d-683d-476f-b751-d359be557d93
:END:

#+begin_src scheme :tangle manifest.scm :eval no
(specifications->manifest
 (list
  "texlive"
  "texlive-base"
  "font-google-roboto"
  "font-lato"
  "font-awesome"))
#+end_src
** TODO Color scheme
:PROPERTIES:
:CREATED:  [2023-07-29 Sat 09:05]
:ID:       a373973c-e31b-4f4b-97fa-bb0e915b2752
:END:

#+BEGIN_SRC latex :noweb-ref latex-config :exports none  :results none :eval no
\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

% Change the page layout if you need to
\\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

% Use roboto and lato for fonts
\\renewcommand{\\familydefault}{\\sfdefault}

% Change the colours if you want to
\\RequirePackage{xcolor}
\\definecolor{dracula-background}{HTML}{141d28}
\\definecolor{dracula-background-secondary-alt}{HTML}{44475a}
\\definecolor{dracula-background-secondary}{HTML}{1e1f29}
\\definecolor{dracula-foreground}{HTML}{f8f8f2}
\\definecolor{dracula-sidebar-background}{HTML}{233346}
\\definecolor{dracula-green}{HTML}{50fa7b}
\\definecolor{dracula-dark-green}{HTML}{b8bb26}
\\definecolor{dracula-violet}{HTML}{bd93f9}
\\definecolor{dracula-magenta}{HTML}{ff79c6}
\\definecolor{dracula-orange}{HTML}{ffb86c}
\\definecolor{dracula-cyan}{HTML}{8be9fd}
\\definecolor{dracula-red}{HTML}{ff5555}
\\definecolor{dracula-yellow}{HTML}{f1fa8c}
\\definecolor{dracula-body-text}{HTML}{C3C3C3}
\\definecolor{dracula-comment}{HTML}{6272a4}
\\definecolor{dracula-page-links}{HTML}{C26EFF}
\\definecolor{dracula-attributes-color}{HTML}{FFFF80}
\\definecolor{dracula-external-links}{HTML}{7CE973}
\\definecolor{dracula-links-hover}{HTML}{92FFFF}
\\definecolor{dracula-hashtags}{HTML}{FFD17E}
\\definecolor{dracula-italics-color}{HTML}{FF7EA2}
\\definecolor{dracula-bold-color}{HTML}{FF4E4E}
\\definecolor{dracula-highlight-text-color}{HTML}{47405E}
\\definecolor{dracula-highlighter}{HTML}{FFFF80}
\\definecolor{dracula-sidebar-text}{HTML}{F2F2F2}
\\definecolor{dracula-page-heading}{HTML}{FFBE49}
\\definecolor{dracula-daily-heading}{HTML}{FFCA6A}
\\definecolor{dracula-headings}{HTML}{F2F2F2}
\\definecolor{dracula-bullets}{HTML}{7A6DAA}
\\definecolor{dracula-closed-bullets}{HTML}{3E445D}
\\definecolor{dracula-references}{HTML}{9E8DDB}
\\definecolor{dracula-block-reference-text}{HTML}{FF9580}
\\definecolor{dracula-namespaces}{HTML}{5EB9FF}
\\definecolor{dracula-all-pages-mentions}{HTML}{FF9580}
\\definecolor{dracula-cursor}{HTML}{F2F2F2}
\\definecolor{dracula-icons}{HTML}{FBCC77}
\\definecolor{dracula-icons-hover}{HTML}{81FFEA}
\\definecolor{dracula-filter-icon}{HTML}{C26EFF}
\\pagecolor{white}
\\colorlet{name}{dracula-violet}
\\colorlet{tagline}{dracula-comment}
\\colorlet{heading}{dracula-namespaces}
\\colorlet{headingrule}{dracula-bullets}
\\colorlet{subheading}{dracula-orange}
\\colorlet{accent}{dracula-page-links}
\\colorlet{hyperlink}{dracula-links-hover}
\\colorlet{emphasis}{dracula-comment}
\\colorlet{body}{dracula-background}

%set link colors
% \\hypersetup{urlcolor=dracula-links-hover}

% Change some fonts, if necessary
\\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
\\renewcommand{\\personalinfofont}{\\footnotesize}
\\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
\\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

% Change the bullets for itemize and rating marker
% for \cvskill if you want to
\\renewcommand{\\itemmarker}{{\\small\\textbullet}}
\\renewcommand{\\ratingmarker}{\\faCircle}
#+END_SRC


** TODO Move LaTeX Config to standard export
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       e6b39d7d-2964-477d-94cc-22a3aba9ddbb
:END:
#+BEGIN_SRC emacs-lisp :noweb yes :exports none  :results none :eval always
(setq org-latex-logfiles-extensions (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf")))

(add-to-list 'org-latex-classes
             '("altacv" "
<<latex-config>>
"

               ("\\cvsection{%s}" . "\\cvsection{%s}")
               ("\\cvevent{%s}" . "\\cvevent{%s}")))
(setq org-latex-packages-alist 'nil)
(setq org-latex-default-packages-alist
      '(("rm" "roboto"  t)
        ("defaultsans" "lato" t)
        ("" "paracol" t)))
#+END_SRC
#+LATEX_CLASS: altacv
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.
#+LATEX_HEADER: \usepackage{luatexja}
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage{fontawesome5}
#+LATEX_HEADER: \usepackage{fontmfizz}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{longtable}
#+LATEX_HEADER: \usepackage{wrapfig}
#+LATEX_HEADER: \usepackage{rotating}
#+LATEX_HEADER: \usepackage[normalem]{ulem}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{amssymb}
#+LATEX_HEADER: \usepackage{capt-of}
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \hypersetup{colorlinks=true, urlcolor=dracula-external-links}
#+LATEX_HEADER: \usepackage[bottom]{footmisc}

** Exporter Settings
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       cc6d2f8b-c29f-45c9-bedd-6b54f2269155
:END:
#+AUTHOR: Daniel Otto
#+EXPORT_FILE_NAME: ./cv-tech-en.pdf
#+OPTIONS: toc:nil title:nil H:1

** Macros
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       181a968d-d2f2-4669-8d43-0097dcd6ebb1
:END:
#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider
#+MACRO: new-page \newpage

* CV header                                                            :ignore:
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       28b6a33c-d0af-4eaf-ba88-f41b0a4f24e3
:END:
** Photo & tagline                                                    :ignore:
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       1f7dd543-9f68-4a9e-a000-27ae33fa036e
:END:
#+begin_export latex
\name{Daniel Otto}
% \photoR{2.8cm}{aidan_portrait.jpeg}
\tagline{Data Analyst}
#+end_export

** Personal info                                                      :ignore:
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       968a66d1-db63-4ec1-8599-624eb6013d2f
:END:
#+begin_export latex
\personalinfo{
  \homepage{www.danielotto.jp}
  \email{contact@danielotto.jp}
  \phone{+81 80 7650 1991}
  \location{Tokyo, Japan}
  \github{nanjigen}
  \linkedin{dmotto}
  \dob{1991/10/18}
}
\makecvheader
#+end_export

* CV Column one                                                        :ignore:
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       dbc07b2d-9bfa-4f95-9215-719a662627b6
:END:
#+begin_export latex
​\begin{paracol}{2}
#+end_export

** Experience
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       bcd96d90-cef6-40c3-9bdd-0e7ab90bdf92
:END:

*** Bilingual English Teacher                                        :ignore:
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 19:07]
:ID:       594ec195-13a8-4f7b-b24a-defc3840765b
:END:

{{{cvevent(English Teacher, KDI, March 2023 -- Ongoing, Tokyo\, Japan)}}}
Teaching position at a bilingual Yochien, where I continue providing linguistics expertise in teaching strategies. Provide interpretation for monolingual co-workers on part of Japanese management.
{{{par-div}}}

*** English Teacher                                                  :ignore:
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 19:07]
:ID:       594ec195-13a8-4f7b-b24a-defc3840765b
:END:
{{{cvevent(English Teacher, NOVA, April 2022 -- March 2023, Tokyo\, Japan)}}}
Plied my understanding of linguistics and specialisation in second language acquisition teaching English to Japanese nationals.
{{{par-div}}}

*** Freelance translator                                             :ignore:
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       38be5e95-8117-48e6-ae8f-bf7f1387c3bc
:END:
{{{cvevent(Freelance translator, self-employed, Sept 2020 -- Ongoing, Tokyo\, Sydney)}}}
Worked on Japanese to English game localisation and linguistic quality assurance over both mobile and console game titles.
{{{par-div}}}

*** Lead Audio-Visual Technician            :ignore:
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       ce053e16-3199-4c78-97c2-39bef6ba5ce0
:END:
{{{cvevent(Lead Audio-Visual Technician, Showtime Productions, Nov 2016 -- Feb 2022, Sydney, Australia)}}}
Lead Audio-Visual Technician at Showtime Productions. Responsibilities encompassed seamless execution and coordination of audio-visual setups for a wide range of events, such as conferences, trade shows, and special gatherings, accommodating audiences of up to 1,500 attendees.

** Technical Skills
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       9eb06397-8706-4782-8e25-64cf64187d5f
:END:
- Software
{{{cvtag(\faLinux GNU/Linux)}}}
{{{cvtag(\faGraph Tableau)}}}
{{{cvtag(\faBarChart Looker)}}}
{{{cvtag(\mfGoogle Google Sheets)}}}
{{{cvtag(\faCloud GCP)}}}
{{{cvtag(\faEmacs Emacs)}}}
{{{cvtag(\faGit)}}}
{{{cvtag(\faGNU GuixSD)}}}
{{{cvtag(\mfVim Vim)}}}
{{{par-div}}}

- Programming
{{{cvtag(\faNotebook Jupyter)}}}
{{{cvtag(\mfPython Python)}}}
{{{cvtag(\faTerraform Terraform)}}}
{{{cvtag(\faRProject R)}}}
{{{cvtag(\faDatabase SQL)}}}
{{{cvtag(\mfClojure Clojure)}}}
{{{cvtag(\mfShell BASH)}}}
{{{cvtag(\LaTeX)}}}
{{{par-div}}}

- Frameworks
{{{cvtag(\faPython pandas)}}}
{{{cvtag(\faPython matplotlib)}}}
{{{cvtag(\faPython plotly)}}}
{{{cvtag(\mfSpark Apache Spark)}}}
{{{cvtag(\faApache Apache Airflow)}}}

{{{new-page}}}
** Projects
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       c250d349-dcb9-4186-b3e7-37580e62d910
:END:
*** Portfolio Website                                                :ignore:
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       6c2239cf-4d30-4490-8387-9e0c3a5bb06b
:END:
{{{cvevent(Profile Website, Personal Project, 2023, Tokyo\, Japan)}}}
- Used Terraform in the Infrastructure as Code model to deploy my static Website to Google Cloud Platform Cloud Storage. Viewable as my website ([[https://www.danielotto.jp][www.danielotto.jp]]) and the related [[https://www.danielotto.jp/posts/static-blog-with-google-cloud-storage-and-weblorg.html][post]].
{{{par-div}}}
{{{divider}}}

*** Google Data Analytics Certificate: Capstone Project              :ignore:
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       e7a5f04b-e691-4266-94bf-11bf215d1d3c
:END:
{{{cvevent(Capstone Project, Coursera, 2023/02 -- Now, Tokyo\, Japan)}}}
- Capstone project for the completion of the Google Data Analytics Professional Certificate. Utilized tools such as =Beautifulsoup4= in order to scrape the SUUMO real estate website and analyze the results. ~Pandas~ was used for data cleaning and loading into a ~sqlite~ database, and with =bs4= and the =Pandas.Dataframe.pipe= method an ETL pipeline was established. Data was then extracted from the database and analysis was performed with an eye towards producing an interactive ~Plotly/Dash~ dashboard website. Viewable [[https://github.com/nanjigen/tokyo-rentals-analysis][here]].
{{{par-div}}}

*** Honours thesis                                                   :ignore:
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       6c2239cf-4d30-4490-8387-9e0c3a5bb06b
:END:
{{{cvevent(Honours Thesis, UNSW, 2018 - 2020, Sydney\, Australia)}}}
- Analysed the JAWL (Japanese Academic Word List) in order to characterize the database and generate Flashcards for use in an eye-tracking learning intervention on L2 learners of Japanese in a university setting. ~openpyxl~ was used to extract data from the =.xlsx= file into a ~pandas~ dataframe. ~NLTK~ was used for P.O.S. tagging. Notebook available on request.

** Volunteering
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       37d186b1-5335-460f-b5b6-dc327832c8a0
:END:
*** EVO Japan                                                        :ignore:
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       d7cd48e6-c377-4c09-a27a-957e92939eb2
:END:
{{{cvevent(EVO Japan, EVO, 2018, Tokyo\, Japan)}}}

*** Various Japan Film Festivals                                     :ignore:
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 18:55]
:ID:       769191f4-66fd-45c8-8fcd-353087e8d66d
:END:
{{{cvevent(Various Japan Film Festivals, Japan Foundation, 2013 -- 2017, Australia)}}}
In Australia
* CV Column two                                                        :ignore:
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       2fefaa8b-614e-49fe-bfa6-7d9e20753f83
:END:
#+begin_export latex
\switchcolumn
#+end_export

** Languages
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       3c16182a-6709-4342-b3b9-eee0d26eadc4
:END:
#+begin_export latex
% \cvsection{Languages}

\cvskill{English - Native}{5}
% \divider

\cvskill{Japanese - JLPT N2}{4}
% \divider

% \cvskill{German}{3}

% %% Yeah I didn't spend too much time making all the
% %% spacing consistent... sorry. Use \smallskip, \medskip,
% %% \bigskip, \vpsace etc to make ajustments.
% \medskip
#+end_export
** Education
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       4e5d2fb3-bfe6-4498-b00b-63bd1d2597d6
:END:
*** Google Data Analytics Professional Certificate                                                 :ignore:
:PROPERTIES:
:CREATED:  [2022-11-01 Tue 11:56]
:ID:       c8617345-4733-4228-9312-a4887d60029c
:END:
{{{cvevent(Google\ Data Analytics Professional Certificate, Coursera, March 2023 - ongoing)}}}
Undertaking the Google Data Analytics Professional Certificate with Coursera, completing the capstone project and bringing my skills inline with industry standards.
{{{par-div}}}
*** Honours in Linguistics                                           :ignore:
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       4f40368f-762a-4961-8429-80f3319bf545
:END:
{{{cvevent(Honours\ in Linguistics, University of New South Wales, Sept 2018 - 2020)}}}
Performed eye-tracking research with human participants, studying the effect of various types of flashcard formatting on the acquisition of academic terms in a second language. I made use of Python to motivate data use, analyse results of captured data and featured these in my thesis and a Jupyter-notebook.
{{{par-div}}}
*** Bachelor of Arts                                                 :ignore:
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       3c21d51e-91e9-4c97-a082-006593c74a40
:END:
{{{cvevent(BA\ in Linguistics and Japanese Studies, University of New South Wales, 2013 - 2017)}}}
Majored in Linguistics and Japanese Studies. This included the study of Japanese and Japanese history and culture. The Linguistics studies focused on pragmatics, semantics, syntactic and morphemic analysis and phonology. Courses were also done in psycholinguistics and second language acquisition.

*** My Life Philosophy                                              :noexport:
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       1f5ac63e-aefb-4a7a-bf22-81b30b575368
:END:
*** Achievements                                                    :noexport:
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       c706263e-1aa0-4790-8c48-346e18ae49f1
:END:

** Referees                                                         :noexport:
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       8223ddb9-633b-4585-9dcf-43417cff1618
:END:

#+begin_export latex
\end{paracol}
#+end_export

* Export                                                             :noexport:
:PROPERTIES:
:CREATED:  [2023-05-15 Mon 09:13]
:ID:       fcd6ef33-a104-4789-8ab1-a403a3bf1034
:END:

#+begin_src elisp :results none :async yes
;; (org-latex-export "cv-tech-en.tex")
(progn
  (org-export-to-file 'latex "cv-tech-en.tex")
  (org-latex-compile "cv-tech-en.tex")
  ;; (display-buffer-fil )
  (display-buffer (find-file-noselect "cv-tech-en.pdf") t))
#+end_src

** No export                                                        :noexport:
:PROPERTIES:
:CREATED:  [2022-10-10 Mon 11:21]
:ID:       a8e3b403-76d9-4a3e-b763-7a8c432868eb
:END:
;* COMMENT local variables

;# Local Variables:
;# org-latex-with-hyperref: nil
;# org-latex-packages-alist: nil
;# org-latex-default-packages-alist: (("rm" "roboto"  t) ("defaultsans" "lato" t) ("" "paracol" t)))
;# End:
