name: Deploy Website

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: profile-website-391909
        export_default_credentials: true

    - name: Deploy to GCS
      run: |
        gsutil rsync -R ./output gs://www.danielotto.jp/output
