name: Deploy Website

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: 'profile-website-391909'

    - name: Setup Emacs
      uses: purcell/setup-emacs@master
      with:
        version: 28.1

    - name: Tangle and publish
      run: |
        emacs --batch \
              --eval "(require 'org)" \
              --eval "(require 'ob-shell)" \
              --eval "(setq org-confirm-babel-evaluate nil)" \
              --eval '(org-babel-tangle-file "profile-page.org")'
        emacs --script publish.el

    - name: Deploy to GCS
      run: |
        gsutil rsync -r ./static/ gs://www.danielotto.jp/static/
        gsutil rsync -r ./output/ gs://www.danielotto.jp/output/
